#!/bin/sh

pulsemixer --get-mute | grep 0 > /dev/null && echo "<span foreground='#81A1C1' size='x-large' >🎵</span> <span size='medium' rise='2pt'>$(pulsemixer --get-volume | awk '{print $1}')%</span>"
