import = ["/home/alex/.config/alacritty/solarized_dark.yml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14

[font.bold]
family = "SourceCodePro"
style = "Bold"

[font.bold_italic]
family = "SourceCodePro"
style = "Bold Italic"

[font.italic]
family = "SourceCodePro"
style = "Italic"

[font.normal]
family = "SourceCodePro"
style = "Normal"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
opacity = 0.8

[window.class]
general = "alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 5
